# Generated by Django 4.2.23 on 2025-08-10 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('joy', '😊 Joyful'), ('peaceful', '😌 Peaceful'), ('excited', '🤗 Excited'), ('content', '😊 Content'), ('neutral', '😐 Neutral'), ('anxious', '😰 Anxious'), ('sad', '😢 Sad'), ('frustrated', '😤 Frustrated'), ('tired', '😴 Tired'), ('other', 'Other')], max_length=20)),
                ('intensity', models.IntegerField(default=5, help_text='1-10 scale')),
                ('note', models.TextField(blank=True, help_text='Optional notes about your mood')),
                ('other_mood', models.CharField(blank=True, help_text="If mood is 'other', describe it", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
